name: Upload Linux Packages to GCP Artifact Registry
description: Sets up GCP authentication and uploads deb/rpm packages to Artifact Registry

inputs:
  gcp-project-id:
    description: "GCP Project ID"
    required: true
  gcp-workload-identity-provider:
    description: "GCP Workload Identity Provider"
    required: true
  gcp-service-account:
    description: "GCP Service Account"
    required: true
  package-directory:
    description: "Directory containing the deb and rpm packages (e.g., 'dist' or 'collector/dist')"
    required: false
    default: "dist"
  repository:
    description: "Base name of the repository in Artifact Registry (will append -apt for deb and -rpm for rpm)"
    required: false
    default: "odigos"
  location:
    description: "GCP location for Artifact Registry"
    required: false
    default: "us-central1"
  access-token-lifetime:
    description: "Access token lifetime for GCP authentication"
    required: false
    default: "1200s"

runs:
  using: composite
  steps:
    - name: Set up GCP
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ inputs.gcp-project-id }}

    - name: Authenticate with Google Cloud
      id: gcp-auth
      uses: google-github-actions/auth@v3
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ inputs.gcp-workload-identity-provider }}
        service_account: ${{ inputs.gcp-service-account }}
        access_token_lifetime: ${{ inputs.access-token-lifetime }}

    - name: Upload deb packages to Artifact Registry
      shell: bash
      run: |
        for deb in ${{ inputs.package-directory }}/*.deb; do
          if [ -f "$deb" ]; then
            echo "Uploading $deb to Artifact Registry..."
            gcloud artifacts apt upload ${{ inputs.repository }}-apt \
              --location=${{ inputs.location }} \
              --source="$deb"
          fi
        done

    - name: Upload rpm packages to Artifact Registry
      shell: bash
      run: |
        for rpm in ${{ inputs.package-directory }}/*.rpm; do
          if [ -f "$rpm" ]; then
            echo "Uploading $rpm to Artifact Registry..."
            gcloud artifacts yum upload ${{ inputs.repository }}-rpm \
              --location=${{ inputs.location }} \
              --source="$rpm"
          fi
        done

