name: "A wrapper for Trivy to scan for vulnerabilities"
description: "Scan container images or filesystem paths for vulnerabilities using Trivy"

inputs:
  image:
    description: "The container image to scan, use complete image reference (e.g., 'nginx:latest' or 'myregistry.com/myimage:tag')"
    required: false
  path:
    description: "Path to the file system to scan (e.g., a directory containing source code or extracted image layers)"
    required: false
  severity-cutoff:
    description: "Comma-separated list of severity levels to include (e.g., 'HIGH,CRITICAL' or 'MEDIUM,HIGH,CRITICAL')"
    required: false
    default: "HIGH,CRITICAL"

runs:
  # Composite implies that the below steps will be run in the same runner as the calling workflow and not in a separate container
  using: composite
  steps:
    - name: Validate Inputs
      if: ${{ (inputs.image == '' && inputs.path == '') || (inputs.image != '' && inputs.path != '') }}
      shell: bash
      run: |
        echo "Error: You must provide either 'image' or 'path' input."
        exit 1

    - name: Scan Image for Vulnerabilities
      if: ${{ inputs.image != '' && inputs.path == '' }}
      id: scan-image
      uses: aquasecurity/trivy-action@0.33.1
      with:
        scan-type: 'image'
        image-ref: ${{ inputs.image }}
        format: 'json'
        output: 'trivy-results.json'
        ignore-unfixed: true
        severity: ${{ inputs.severity-cutoff }}

    - name: Scan Path for Vulnerabilities
      if: ${{ inputs.path != '' && inputs.image == '' }}
      id: scan-path
      uses: aquasecurity/trivy-action@0.33.1
      with:
        scan-type: 'fs'
        scan-ref: ${{ inputs.path }}
        format: 'json'
        output: 'trivy-results.json'
        ignore-unfixed: true
        severity: ${{ inputs.severity-cutoff }}

    - name: Display in Summary
      if: always()
      shell: bash
      run: |
        echo "## ðŸ” Vulnerability Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        JSON_FILE="trivy-results.json"
        if [ -f "$JSON_FILE" ]; then
          # Trivy JSON format has Results array with Vulnerabilities inside each result
          TOTAL=$(jq '[.Results[]?.Vulnerabilities // [] | .[]] | length' "$JSON_FILE")
          CRITICAL=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "CRITICAL")] | length' "$JSON_FILE")
          HIGH=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "HIGH")] | length' "$JSON_FILE")
          MEDIUM=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "MEDIUM")] | length' "$JSON_FILE")
          
          echo "| Severity | Count |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| ðŸ”´ Critical | $CRITICAL |" >> $GITHUB_STEP_SUMMARY
          echo "| ðŸŸ  High | $HIGH |" >> $GITHUB_STEP_SUMMARY
          echo "| ðŸŸ¡ Medium | $MEDIUM |" >> $GITHUB_STEP_SUMMARY
          echo "| **Total** | **$TOTAL** |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Critical vulnerabilities
          if [ "$CRITICAL" -gt 0 ]; then
            echo "### ðŸ”´ Critical Vulnerabilities ($CRITICAL)" >> $GITHUB_STEP_SUMMARY
            jq -r '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "CRITICAL")] | .[] | "- **\(.VulnerabilityID)** in `\(.PkgName)@\(.InstalledVersion)` (Fixed: \(.FixedVersion // "N/A"))"' "$JSON_FILE" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
          
          # High vulnerabilities
          if [ "$HIGH" -gt 0 ]; then
            echo "### ðŸŸ  High Vulnerabilities ($HIGH)" >> $GITHUB_STEP_SUMMARY
            jq -r '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "HIGH")] | .[] | "- **\(.VulnerabilityID)** in `\(.PkgName)@\(.InstalledVersion)` (Fixed: \(.FixedVersion // "N/A"))"' "$JSON_FILE" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
          
          # Medium vulnerabilities
          if [ "$MEDIUM" -gt 0 ]; then
            echo "<details><summary>ðŸŸ¡ Medium Vulnerabilities ($MEDIUM)</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            jq -r '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "MEDIUM")] | .[] | "- **\(.VulnerabilityID)** in `\(.PkgName)@\(.InstalledVersion)` (Fixed: \(.FixedVersion // "N/A"))"' "$JSON_FILE" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          fi

          # If we had high or critical vulnerabilities - fail the step
          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
            exit 1
          fi
        else
          echo "âœ… No vulnerabilities found!" >> $GITHUB_STEP_SUMMARY
        fi
