name: "A wrapper for Grype to scan for vulnerabilities in container images"
description: "Scan container images for vulnerabilities using Grype"

inputs:
  image:
    description: "The container image to scan, use complete image reference (e.g., 'nginx:latest' or 'myregistry.com/myimage:tag')"
    required: false
  path:
    description: "Path to the file system to scan (e.g., a directory containing extracted image layers)"
    required: false

runs:
  # Composite implies that the below steps will be run in the same runner as the calling workflow and not in a separate container
  using: composite
  steps:
    - name: Validate Inputs
      if: ${{ (inputs.image == '' && inputs.path == '') || (inputs.image != '' && inputs.path != '') }}
      shell: bash
      run: |
        echo "Error: You must provide either 'image' or 'path' input."
        exit 1
    - if: ${{ inputs.image != '' && inputs.path == '' }}
      uses: anchore/scan-action@8d2fce09422cd6037e577f4130e9b925e9a37175
      name: Scan for Vulnerabilities
      id: scan-image
      continue-on-error: true
      with:
        image: ${{ inputs.image }}
        output-format: "json"
        fail-build: true
        severity-cutoff: "high"
        only-fixed: true

    - if: ${{ inputs.path != '' && inputs.image == '' }}
      uses: anchore/scan-action@8d2fce09422cd6037e577f4130e9b925e9a37175
      name: Scan for Vulnerabilities
      id: scan-path
      continue-on-error: true
      with:
        path: ${{ inputs.path }}
        output-format: "json"
        fail-build: true
        severity-cutoff: "high"
        only-fixed: true

    - name: Display in Summary
      if: always()
      shell: bash
      run: |
        echo "## ðŸ” Vulnerability Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        JSON_FILE="${{ steps.scan-image.outputs.json-file || steps.scan-path.outputs.json-file }}"
        if [ -f "$JSON_FILE" ]; then
          TOTAL=$(jq '.matches | length' "$JSON_FILE")
          CRITICAL=$(jq '[.matches[] | select(.vulnerability.severity == "Critical")] | length' "$JSON_FILE")
          HIGH=$(jq '[.matches[] | select(.vulnerability.severity == "High")] | length' "$JSON_FILE")
          MEDIUM=$(jq '[.matches[] | select(.vulnerability.severity == "Medium")] | length' "$JSON_FILE")
          
          echo "| Severity | Count |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| ðŸ”´ Critical | $CRITICAL |" >> $GITHUB_STEP_SUMMARY
          echo "| ðŸŸ  High | $HIGH |" >> $GITHUB_STEP_SUMMARY
          echo "| ðŸŸ¡ Medium | $MEDIUM |" >> $GITHUB_STEP_SUMMARY
          echo "| **Total** | **$TOTAL** |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Critical vulnerabilities
          if [ "$CRITICAL" -gt 0 ]; then
            echo "### ðŸ”´ Critical Vulnerabilities ($CRITICAL)" >> $GITHUB_STEP_SUMMARY
            jq -r '.matches[] | select(.vulnerability.severity == "Critical") | "- **\(.vulnerability.id)** in `\(.artifact.name)@\(.artifact.version)` (Fixed: \(.vulnerability.fix.versions[0] // "N/A"))"' "$JSON_FILE" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
          
          # High vulnerabilities
          if [ "$HIGH" -gt 0 ]; then
            echo "### ðŸŸ  High Vulnerabilities ($HIGH)" >> $GITHUB_STEP_SUMMARY
            jq -r '.matches[] | select(.vulnerability.severity == "High") | "- **\(.vulnerability.id)** in `\(.artifact.name)@\(.artifact.version)` (Fixed: \(.vulnerability.fix.versions[0] // "N/A"))"' "$JSON_FILE" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
          
          # Medium vulnerabilities
          if [ "$MEDIUM" -gt 0 ]; then
            echo "<details><summary>ðŸŸ¡ Medium Vulnerabilities ($MEDIUM)</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            jq -r '.matches[] | select(.vulnerability.severity == "Medium") | "- **\(.vulnerability.id)** in `\(.artifact.name)@\(.artifact.version)` (Fixed: \(.vulnerability.fix.versions[0] // "N/A"))"' "$JSON_FILE" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          fi

          # If we had high or critical vulnerabilities - fail the step
          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
            exit 1
          fi
        else
          echo "âœ… No vulnerabilities found!" >> $GITHUB_STEP_SUMMARY
        fi
