name: 'Slack Release Notification'
description: 'Send Slack notifications based on job status for release updates'

inputs:
  webhook-url:
    description: 'Slack webhook URL'
    required: true
  success-description:
    description: 'Description message for successful release step notification'
    required: true
  failure-description:
    description: 'Description message for failed release step notification'
    required: true
  tag:
    description: 'Release tag'
    required: false
  release-pr-link:
    description: 'If this update includes a release PR, this is the link to it'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Determine Job Status and Notify Slack
      shell: bash
      run: |
        REPO="${{ github.repository }}" # <owner>/<repository_name>
        REPOSITORY_NAME=$(basename "$REPO") # <repository_name>

        if [ "${{ job.status }}" = "success" ]; then
          echo "Release notification SUCCESS"
          PAYLOAD=$(jq -n \
            --arg desc "✅ ${{ inputs.success-description }}" \
            --arg tag "${{ inputs.tag }}" \
            --arg repo_name "$REPOSITORY_NAME" \
            --arg release_pr_link "${{ inputs.release-pr-link }}" \
            '{description: $desc, tag: $tag, repo_name: $repo_name, release_pr_link: $release_pr_link}')
          echo "Success payload: $PAYLOAD"
          curl -X POST -H 'Content-type: application/json' \
            --data "$PAYLOAD" \
            "${{ inputs.webhook-url }}"
        else
          echo "Release notification FAILURE (ci workflow failed or cancelled)"
          RUN_ID="${{ github.run_id }}"

          PAYLOAD=$(jq -n \
            --arg link "https://github.com/$REPO/actions/runs/$RUN_ID" \
            --arg desc "❌ ${{ inputs.failure-description }}" \
            --arg tag "${{ inputs.tag }}" \
            --arg repo_name "$REPOSITORY_NAME" \
            '{link: $link, description: $desc, tag: $tag, repo_name: $repo_name}')

          echo "Failure payload: $PAYLOAD"
          curl -X POST -H 'Content-type: application/json' \
            --data "$PAYLOAD" \
            "${{ inputs.webhook-url }}"
        fi
