name: Upload Linux Packages to AWS S3
description: Sets up AWS OIDC authentication and uploads deb/rpm packages to S3

inputs:
  aws-role-arn:
    description: "AWS IAM Role ARN for OIDC authentication"
    required: true
  aws-region:
    description: "AWS Region"
    required: false
    default: "us-east-1"
  bucket-name:
    description: "S3 Bucket Name"
    required: true
  agent-type:
    description: "Agent type: 'vmagent' or 'otelcol'"
    required: true
  version:
    description: "Version of the release (e.g., '0.1.56')"
    required: true
  package-directory:
    description: "Directory containing the deb and rpm packages (e.g., 'dist' or 'collector/dist')"
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - name: Upload deb packages to S3
      shell: bash
      run: |
        S3_BASE_PATH="s3://${{ inputs.bucket-name }}/odigos-${{ inputs.agent-type }}/${{ inputs.version }}/apt"

        for deb in ${{ inputs.package-directory }}/*.deb; do
          if [ -f "$deb" ]; then
            filename=$(basename "$deb")
            echo "Uploading $deb to $S3_BASE_PATH/$filename..."
            aws s3 cp "$deb" "$S3_BASE_PATH/$filename"
          fi
        done

    - name: Upload rpm packages to S3
      shell: bash
      run: |
        S3_BASE_PATH="s3://${{ inputs.bucket-name }}/odigos-${{ inputs.agent-type }}/${{ inputs.version }}/rpm"

        for rpm in ${{ inputs.package-directory }}/*.rpm; do
          if [ -f "$rpm" ]; then
            filename=$(basename "$rpm")
            echo "Uploading $rpm to $S3_BASE_PATH/$filename..."
            aws s3 cp "$rpm" "$S3_BASE_PATH/$filename"
          fi
        done

