name: PR Policy

permissions:
  pull-requests: read
  statuses: write

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  require-linear:
    uses: odigos/ci-core/.github/workflows/require-linear.yml@v1
    secrets: inherit
