name: Validate & Tag Release

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver tag to create (e.g., v1.0.2)"
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint
        uses: raven-actions/actionlint@v2
      - name: yamllint
        run: pipx run yamllint .

  tag:
    needs: [lint]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ensure full history for tagging
      - name: Config git identity
        run: |
          git config user.name  "odigos-ci-bot"
          git config user.email "ci@odigos.io"
      - name: Create & push tag
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}
