# .github/workflows/require-linear.yml
name: Require Linked Linear Issue

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      linear-prefix-regex:
        description: "Regex matching allowed Linear team prefixes (include trailing dash each)"
        required: false
        default: '(CORE-|PLAT-|PRD-|RUN-|GEN-|DEVOPS-)'
        type: string
      bot-accounts-json:
        description: "JSON array of GitHub usernames to skip check for"
        required: false
        default: '["dependabot[bot]","renovate[bot]","odigos-bot","github-actions[bot]","keyval-release-bot"]'
        type: string
    secrets: {}
    # We use caller GITHUB_TOKEN via secrets: inherit in caller.

jobs:
  linear-check:
    # Run only for repos in org AND when caller's triggering event was pull_request
    if: ${{ github.repository_owner == 'odigos-io' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      statuses: write

    steps:
      - name: Skip Linear check for bots
        if: ${{ github.event.pull_request.user.type == 'Bot' ||
                contains(fromJson(inputs.bot-accounts-json), github.actor) }}
        run: echo "PR opened by ${{ github.actor }} – Linear check skipped."

      - name: Ensure PR links a Linear issue
        if: ${{ github.event.pull_request.user.type != 'Bot' &&
                !contains(fromJson(inputs.bot-accounts-json), github.actor) }}
        uses: copilotmoney/linear-pr-check@1.0.0
        with:
          prefix:       ${{ inputs.linear-prefix-regex }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
